### ISSUE TITLE
ct_cleanup deletes more files it should

### ISSUE THREAD

**Issue by lukaszachy** [sclorg/varnish-container#111]
After varnish test/run  finishes files in / are removed. Looks that `CID_FILE_DIR` is empty or unset and `for cid_file in "$CID_FILE_DIR"/*` iterates over files in /.

See https://github.com/sclorg/container-common-scripts/blob/master/test-lib.sh#L35

**Comment by zmiklank** [comment]
Thank you for filling the issue.
The issue has been addressed in linked PRs. However they need to be tested and reviewed before merging.

**Comment by zmiklank** [comment]
It could also make sense to rework the varnish container to use $CID_FILE_DIR someday in the future.
But nevertheless the steps in mentioned PRs are still needed.
