### ISSUE TITLE
Fedora image out of date, centos container running deprecated versions

### ISSUE THREAD

**Issue by ibotty** [sclorg/varnish-container#117]
The Fedora image is 35, which is EOL.  The varnish in the centos8 and centos9 containers is out of date:
quay.io/sclorg/varnish-6-c8s is using varnish 6.0.8-1 (which most likely is missing security updates).
quay.io/sclorg/varnish-6-c9s uses varnish-6.6.2-3 which is deprecated (not being LTS).

Is there intention on updating it?

**Comment by hhorak** [comment]
Thanks for reporting this.

Fedora image is now updated, but only for Varnish 7:

```
$ podman run -ti --rm quay.io/fedora/varnish-7 rpm -q varnish
varnish-7.1.2-1.fc37.x86_64
```

We don't intend to update Varnish 6 for Fedora any more, as there is no Varnish 6 on Fedora 37, that we currently use as a base for fedora images.

For CentOS Stream 8 and 9, I see we're having the latest builds that are available in RHEL, and thus also in CentOS Stream:

```
$ podman run -ti --rm quay.io/sclorg/varnish-6-c8s rpm -q varnish
varnish-6.0.8-1.module_el8.5.0+995+944219f1.x86_64
$ podman run -ti --rm quay.io/sclorg/varnish-6-c9s rpm -q varnish
varnish-6.6.2-3.el9.x86_64
``` 

If you need a newer version, it must be first updated in RHEL, as we do not build our own RPM packages for the container images, we only take the RHEL/CentOS Stream content.
