### ISSUE TITLE
Can't run since is giving permission denied error

### ISSUE THREAD

**Issue by sebas5384** [sclorg/varnish-container#23]
Here's what I tried till now:

1. Running the example instructed in the docs just adding 
```
# s2i build https://github.com/sclorg/varnish-container.git --context-dir=4/test/test-app/ registry.access.redhat.com/rhscl/varnish-4-rhel7 sample-server
# docker run -p 8080:8080 sample-server
Message from VCC-compiler:
Not running as root, no priv-sep
Message from C-compiler:
Not running as root, no priv-sep
Message from dlopen:
Not running as root, no priv-sep
Mmap error _.vsm.1: Permission denied
```

2. Tried to build it using a different default.vcl but the result is the same error.

I'm doing something wrong? or this images doesn't work?

Any help would be appreciated, thanks.

**Comment by omron93** [comment]
@sebas5384 Hi, I've tried the same command without problem.

Please provide more information about your environment.

**Comment by phracek** [comment]
Marking this issue as obsolete.

Feel free to reopen in if the problem still appears with varnish-6.
