### ISSUE TITLE
registry.centos.org/centos/vernish-4:centos7 build is broken

### ISSUE THREAD

**Issue by bamachrn** [sclorg/varnish-container#33]
build for centos/vernish-4:centos7 is broken since last few days. it is failing in the step 8.
```
Step 8 : COPY 4/s2i/bin/ $STI_SCRIPTS_PATH
lstat 4/s2i/bin/: no such file or directory
```
it seems there is a symbolic link, which is not getting resolved.
```
lrwxrwxrwx 1 bamachrn bamachrn    7 Jan 31 18:42 s2i -> ../s2i/
```

build log: https://registry.centos.org/pipeline-logs/OWQzNTNhMzUxZW/build_logs.txt
 This is getting built based on [this](https://github.com/CentOS/container-index/blob/master/index.d/centos.yml#L1178-L1191) entry in [container-index](https://github.com/CentOS/container-index)

**Comment by mohammedzee1000** [comment]
@hhorak ^

**Comment by bamachrn** [comment]
@omron93 in this case I believe adding proper `build_context` to https://github.com/CentOS/container-index/blob/master/index.d/centos.yml#L1187 will solve the issue. This will also make sure this image builds  similarly in all the places.
I believe the `build_context` in this case is `../4/` let me test it and update the entry for the same.

**Comment by omron93** [comment]
>  this case I believe adding proper build_context to https://github.com/CentOS/container-index/blob/master/index.d/centos.yml#L1187 will solve the issue.

@bamachrn I don't know how `build_context` is used.

So I'll explain how we build this image:
In this repo `cd 4/; docker build -f Dockerfile ..` or it could be also possible by this ` docker build -f 4/Dockerfile .`

**Comment by bamachrn** [comment]
> In this repo cd 4/; docker build -f Dockerfile .. 
```
    git-path: 4/
    target-file: Dockerfile
    build-context: ../
```
>  it could be also possible by this docker build -f 4/Dockerfile .
```
    git-path: /
    target-file: 4/Dockerfile
    build-context: ./
```
`git-path` is where to `cd`, `target-file` is what is location of `Dockerfile` which is kept after `-f` ,  `build-context` is same as you said.

@omron93 would you like to raise a PR in [container-index](https://github.com/CentOS/container-index) for this? as this image is maintained by the sclo guys, @hhorak had updated last time.

**Comment by omron93** [comment]
@bamachrn PR created - https://github.com/CentOS/container-index/pull/277

**Comment by bamachrn** [comment]
@omron93 PR merged, lets wait for the image to get built before closing the issue.

**Comment by navidshaikh** [comment]
the build is still failing after updating the build context

excerpt from build logs https://registry.centos.org/pipeline-logs/YjgzNzg5N2Y2ZG/build_logs.txt
```
Step 8 : COPY 4/s2i/bin/ $STI_SCRIPTS_PATH
lstat 4/s2i/bin/: no such file or directory
```

ping @bamachrn

**Comment by navidshaikh** [comment]
> the build is still failing after updating the build context

This is a service side issue with [this fix](https://github.com/CentOS/container-pipeline-service/pull/467) already in place, going through a staging environment for testing. One it lands at production service, the container should resume building.

**Comment by phracek** [comment]
Version 4 is not supported at all. It reached EOL. Please use varnish version 6, which is supported.
