### ISSUE TITLE
Send varnishncsa output to stdout

### ISSUE THREAD

**Issue by michaelryanmcneill** [sclorg/varnish-container#40]
It would be ideal to send varnishncsa output to stdout so it gets logged appropriately and shows up in a normal apache format for parsing using Kibana (or Splunk).

**Comment by phracek** [comment]
@michaelryanmcneill I don't know if it is still valid for varnish-6. What `varnishncsa` logs do you need? Can you please provide more details? Thank you.

Feel free to file a pull request, so we can imagine, what logs can be useful for users

**Comment by phracek** [comment]
Closing issue, because we do not have enough capacity to implement it. Feel free to re-open it, in case it makes sense or even send a pull request so we can review it.
