### ISSUE TITLE
Assemble process should be cleaner

### ISSUE THREAD

**Issue by michaelryanmcneill** [sclorg/varnish-container#42]
Instead of copying all the files, we should follow what https://github.com/sclorg/s2i-php-container/blob/master/7.0/s2i/bin/assemble does, which is:

```
shopt -s dotglob
echo "---> Installing application source..."
mv /tmp/src/* ./
```

This prevents moving the .git directory with it. 

In addition, I'm not sure I see a need to cat the default.vcl file on each build. What is the use besides the occasional debugging?

**Comment by omron93** [comment]
@michaelryanmcneill Thanks. PullRequests are really welcomed.

> Instead of copying all the files, we should follow what https://github.com/sclorg/s2i-php-container/blob/master/7.0/s2i/bin/assemble does, which is:

`rsync` will probably be used. See ongoing discussion https://github.com/sclorg/s2i-nodejs-container/pull/182

**Comment by phracek** [comment]
@michaelryanmcneill Can you please file a PR, including test suite?
