### ISSUE TITLE
Add imagestream for varnish

### ISSUE THREAD

**Issue by pvalena** [sclorg/varnish-container#47]
I expect it'll look similar to [nginx one](https://github.com/sclorg/nginx-container/tree/master/imagestreams).

**Comment by hhorak** [comment]
Yeah, that would make sense.

**Comment by phracek** [comment]
The imagestreams are already present.

As for CentOS 7: https://github.com/sclorg/varnish-container/blob/master/imagestreams/varnish-centos.json
as for RHEL 7 and RHEL 8: https://github.com/sclorg/varnish-container/blob/master/imagestreams/varnish-rhel.json

Closing this issue. Feel free to reopen it, in case it is still valid.
